sudo: required
services:
  - docker

before_install:
  - docker build -t scowil101/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true scowil101/react-test npm test

after_sucess:
  - docker build -t scowil101/multi-client ./client
  - docker build -t scowil101/multi-nginx ./nginx
  - docker build -t scowil101/multi-server ./server
  - docker build -t scowil101/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push scowil101/multi-client
  - docker push scowil101/multi-nginx
  - docker push scowil101/multi-server
  - docker push scowil101/multi-worker
  